apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-order-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-order
  template:
    metadata:
      labels:
        app: ms-order
    spec:
      containers:
      - name: ms-order-container
        image: felipepxavier/api-ms-order:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ms-order-config
        - secretRef:
            name: ms-order-secrets
